ip-check:
  api-url: "http://ip-api.com"

find-my-ip-address:
  api-url: "http://checkip.amazonaws.com"

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=giftandgo
